// src/lib/profileConfig.ts
// Configuration for each account type's public profile behavior

import { AccountType } from '../types/public-profile';

export interface ProfileConfig {
  label: string;
  icon: string;
  color: string;
  badgeColor: string;
  description: string;
  publicFields: string[];
  privateFields: string[];
  availableTabs: string[];
  canMessage: boolean;
  canCall: boolean;
  canBookAppointment: boolean;
  canPurchase: boolean;
  requiresVerification: boolean;
}

export const PROFILE_CONFIG: Record<AccountType, ProfileConfig> = {
  user: {
    label: 'Customer',
    icon: 'User',
    color: 'bg-blue-500',
    badgeColor: 'text-blue-600',
    description: 'Platform member',
    publicFields: ['full_name', 'avatar_url', 'member_since', 'reviews_written'],
    privateFields: ['email', 'phone', 'total_orders', 'total_spent'],
    availableTabs: ['overview', 'reviews'],
    canMessage: true,
    canCall: false,
    canBookAppointment: false,
    canPurchase: false,
    requiresVerification: false,
  },
  customer: {
    label: 'Customer',
    icon: 'User',
    color: 'bg-blue-500',
    badgeColor: 'text-blue-600',
    description: 'Product buyer',
    publicFields: ['full_name', 'avatar_url', 'member_since'],
    privateFields: ['email', 'phone', 'total_orders', 'total_spent'],
    availableTabs: ['overview'],
    canMessage: true,
    canCall: false,
    canBookAppointment: false,
    canPurchase: false,
    requiresVerification: false,
  },
  seller: {
    label: 'Seller',
    icon: 'Store',
    color: 'bg-green-500',
    badgeColor: 'text-green-600',
    description: 'Product merchant',
    publicFields: ['store_name', 'location', 'total_products', 'average_rating', 'review_count'],
    privateFields: ['email', 'phone', 'total_sales'],
    availableTabs: ['overview', 'products', 'reviews', 'about', 'contact'],
    canMessage: true,
    canCall: true,
    canBookAppointment: false,
    canPurchase: true,
    requiresVerification: true,
  },
  factory: {
    label: 'Factory',
    icon: 'Factory',
    color: 'bg-orange-500',
    badgeColor: 'text-orange-600',
    description: 'Manufacturing partner',
    publicFields: ['company_name', 'production_capacity', 'specialization', 'is_verified'],
    privateFields: ['email', 'phone', 'business_license_url'],
    availableTabs: ['overview', 'products', 'reviews', 'about', 'contact'],
    canMessage: true,
    canCall: true,
    canBookAppointment: false,
    canPurchase: true,
    requiresVerification: true,
  },
  middleman: {
    label: 'Middle Man',
    icon: 'Handshake',
    color: 'bg-purple-500',
    badgeColor: 'text-purple-600',
    description: 'Broker/Commission agent',
    publicFields: ['company_name', 'commission_rate', 'total_deals', 'average_rating'],
    privateFields: ['email', 'phone', 'total_earnings', 'pending_earnings'],
    availableTabs: ['overview', 'reviews', 'about', 'contact'],
    canMessage: true,
    canCall: true,
    canBookAppointment: false,
    canPurchase: false,
    requiresVerification: true,
  },
  freelancer: {
    label: 'Freelancer',
    icon: 'Laptop',
    color: 'bg-indigo-500',
    badgeColor: 'text-indigo-600',
    description: 'Independent service provider',
    publicFields: ['display_name', 'tagline', 'skills', 'hourly_rate', 'average_rating'],
    privateFields: ['email', 'phone', 'total_earnings'],
    availableTabs: ['overview', 'portfolio', 'services', 'reviews', 'about', 'contact'],
    canMessage: true,
    canCall: true,
    canBookAppointment: true,
    canPurchase: true,
    requiresVerification: true,
  },
  service_provider: {
    label: 'Service Provider',
    icon: 'Briefcase',
    color: 'bg-teal-500',
    badgeColor: 'text-teal-600',
    description: 'Business service provider',
    publicFields: ['provider_name', 'specialties', 'average_rating', 'is_verified'],
    privateFields: ['email', 'phone', 'tax_id', 'registration_number'],
    availableTabs: ['overview', 'services', 'reviews', 'about', 'contact'],
    canMessage: true,
    canCall: true,
    canBookAppointment: true,
    canPurchase: true,
    requiresVerification: true,
  },
  delivery_driver: {
    label: 'Delivery Driver',
    icon: 'Truck',
    color: 'bg-yellow-500',
    badgeColor: 'text-yellow-600',
    description: 'Logistics personnel',
    publicFields: ['vehicle_type', 'rating', 'total_deliveries', 'is_verified'],
    privateFields: ['email', 'phone', 'driver_license_url', 'vehicle_number'],
    availableTabs: ['overview', 'about'],
    canMessage: true,
    canCall: true,
    canBookAppointment: false,
    canPurchase: false,
    requiresVerification: true,
  },
  doctor: {
    label: 'Doctor',
    icon: 'Stethoscope',
    color: 'bg-red-600',
    badgeColor: 'text-red-700',
    description: 'Medical practitioner',
    publicFields: ['specialization', 'consultation_fee', 'years_of_experience', 'average_rating'],
    privateFields: ['email', 'phone', 'license_number'],
    availableTabs: ['overview', 'appointments', 'reviews', 'about', 'contact'],
    canMessage: true,
    canCall: true,
    canBookAppointment: true,
    canPurchase: false,
    requiresVerification: true,
  },
  patient: {
    label: 'Patient',
    icon: 'Heart',
    color: 'bg-pink-500',
    badgeColor: 'text-pink-600',
    description: 'Healthcare consumer',
    publicFields: ['full_name', 'avatar_url'],
    privateFields: ['email', 'phone', 'date_of_birth', 'blood_type', 'medical_history'],
    availableTabs: ['overview'],
    canMessage: false,
    canCall: false,
    canBookAppointment: false,
    canPurchase: false,
    requiresVerification: false,
  },
  pharmacy: {
    label: 'Pharmacy',
    icon: 'Pill',
    color: 'bg-emerald-500',
    badgeColor: 'text-emerald-600',
    description: 'Medicine vendor',
    publicFields: ['pharmacy_name', 'location', 'operating_hours', 'delivery_available'],
    privateFields: ['email', 'phone', 'license_number', 'license_document_url'],
    availableTabs: ['overview', 'medicines', 'reviews', 'about', 'contact'],
    canMessage: true,
    canCall: true,
    canBookAppointment: false,
    canPurchase: true,
    requiresVerification: true,
  },
  admin: {
    label: 'Admin',
    icon: 'Shield',
    color: 'bg-gray-700',
    badgeColor: 'text-gray-800',
    description: 'Platform administrator',
    publicFields: ['full_name', 'avatar_url'],
    privateFields: ['email', 'phone'],
    availableTabs: ['overview'],
    canMessage: true,
    canCall: false,
    canBookAppointment: false,
    canPurchase: false,
    requiresVerification: true,
  },
};

// Verification badge levels
export const VERIFICATION_LEVELS = {
  none: { label: 'Unverified', color: 'bg-gray-200 text-gray-600' },
  basic: { label: 'Basic Verified', color: 'bg-blue-100 text-blue-700' },
  premium: { label: 'Premium Verified', color: 'bg-green-100 text-green-700' },
  enterprise: { label: 'Enterprise Verified', color: 'bg-purple-100 text-purple-700' },
};
